extends:
  - theme-check:recommended

ignore:
  - ".github/**"
  - "docs/**"
  - "scripts/**"
  - "node_modules/**"
  - "test-results/**"
  - "coverage/**"

OrphanedSnippet:
  ignore:
    - "snippets/rhino-icon.liquid"
